"""
Django settings for Voting_System project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9m%d+0(kb!)f=($sfxld#@g!s#r3+7by%2)*+a6il+-p4&p4i('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['online-voting-system-x4i2.onrender.com', 'localhost', '127.0.0.1', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party applications
    'rest_framework',
    'corsheaders',
    
    # Local application
    'voting',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Kept on top to handle CORS requests first
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ─── CORS CONFIGURATION UPDATED ───
# यहाँ हमने टेस्टिंग के लिए सब कुछ अलाउ कर दिया है ताकि वर्सेल से कनेक्शन तुरंत बन जाए!
CORS_ALLOW_ALL_ORIGINS = True

# अगर बाद में तुम सिर्फ वर्सेल को अलाउ करना चाहो तो नीचे वाली लाइन्स अनकमेंट कर सकते हो:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "https://online-voting-system-1eal.vercel.app",
# ]
# ──────────────────────────────────

ROOT_URLCONF = 'Voting_System.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Voting_System.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# ─── LIVE POSTGRESQL DATABASE CONFIGURATION ───
DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://neondb_owner:npg_ubleQH6dYrG9@ep-round-leaf-atuppltg.c-9.us-east-1.aws.neon.tech/neondb',
        conn_max_age=600,
        ssl_require=True
    )
}
# ──────────────────────────────────────────────────


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Django REST Framework & Simple JWT Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# Custom User Model definition
AUTH_USER_MODEL = 'voting.CustomUser'


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'vt464670@gmail.com'      
EMAIL_HOST_PASSWORD = 'eivf icvq nmlm jioy'