# Generated by Django 6.0.6 on 2026-08-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='General Election', max_length=200)),
                ('end_time', models.DateTimeField()),
                ('is_declared', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(max_length=100),
        ),
    ]
